# Copyright 2022 loongcollector Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "loongcollector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "loongcollector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "loongcollector.selectorLabels" . | nindent 8 }}
    spec:
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            - name: ALIYUN_LOG_ENV_TAGS
              value: _node_name_|_node_ip_
            - name: _node_name_
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: _node_ip_
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: cpu_usage_limit
              value: "9999"
            - name: mem_usage_limit
              value: "9999"
            - name: default_access_key_id # accesskey id if you want to flush to SLS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: access_key_id
                  optional: true
            - name: default_access_key # accesskey secret if you want to flush to SLS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: access_key
                  optional: true
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
            - mountPath: /usr/local/loongcollector/conf/continuous_pipeline_config/local # mount config dir
              name: user-config
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/local/loongcollector/loongcollector_control.sh
                  - stop
                  - "3"
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ .Values.hostNetwork }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{-  toYaml .Values.volumes | nindent 8 }}
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-user-cm
          name: user-config